name: Create Release on Version Commit

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        default: ''

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Get previous release tag
        id: get_previous_tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "previous_tag=$PREVIOUS_TAG" >> $GITHUB_ENV
        shell: bash

      - name: Generate changelog
        id: changelog
        run: |
          if [ "$PREVIOUS_TAG" != "" ]; then
            git log $PREVIOUS_TAG..HEAD --oneline > changelog.txt
          else
            git log --oneline > changelog.txt
          fi
          echo "changelog=$(cat changelog.txt)" >> $GITHUB_ENV
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Changes since last release:
            ```
            ${{ env.changelog }}
            ```
          tag_name: "v${{ github.event.inputs.version }}"
          name: "Release v${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
